dist: trusty
sudo: false
group: beta
language: c
os:
  - osx

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libsodium nim ; fi

script:
    - nim c -p=. --cc:$CC -r test_sodium.nim

branches:
  except:
    - gh-pages
